---
abstract: 'Class for making HTTP requests'
author:
  - 'Lincoln Ombelets <lincdog85@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Client
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  HTTP::Lite: 0
resources:
  repository: git://github.com/neilbowers/HTTP-Client.git
version: 1.55
